---
- hosts: "all"
  gather_facts: yes
  become: true
  tasks:
  - name: OS family
    debug: msg="{{ ansible_facts['os_family'] }}"
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version }}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
  - name: do smth in shell
    shell:
      cmd: "systemctl is-system-running | grep -E 'running|degraded'"
    register: pena
  - name: echo pena
    debug: msg="{{ pena }}"

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

